### ISSUE TITLE
issue with XCode 4.5 DP4

### ISSUE THREAD

**Issue by krzyzanowskim** [pierrotsmnrd/grabKit#5]
grabKit/grabKitSources/serviceGrabbers/flickrGrabber/GRKFlickrQuery.h:36:39: Cannot find protocol declaration for 'OFFlickrAPIRequestDelegate'

**Comment by pierrotsmnrd** [comment]
Can you help fixing this please ? I don't have switched to XCode 4.5 yet.

**Comment by krzyzanowskim** [comment]
I think it's already fixed in objectiveflickr you could consider switch to submodule instead hardcopy. Here is some discussion about the issue: https://groups.google.com/forum/#!msg/objectiveflickr/wWwA8jiNNlc/wGpOtV6lN-4J

**Comment by pierrotsmnrd** [comment]
For some reasons, I can't use submodules for every external libraries. For example, the new FB iOS SDK is not available on GitHub, neither is GData's Objective-C Library. Furthermore, GrabKit needs only a tiny part of GData library (which is REALLY big, as it covers all the services of Google ...)

So, instead of switching to submodules only for ObjectiveFlickR, I prefer hard-copying all of them.

Thanks for reporting and for your quick help :) I'll commit this soon :)

**Comment by pierrotsmnrd** [comment]
Fixed in GrabKit v1.2.
Thanks for your help krzak ! :)
